# Site settings ...
uri: github.io
url: https://csaroff
name: Chaskin Saroff
title: "Chaskin's Homepage"
author: csaroff
baseurl: ""
keywords: "climb, node, code, software, math, mathematics, research, rock climb, chaskin, saroff, chaskin saroff"
description: "Hey, I'm Chaskin.  I write software services for IBM Bluemix.  In my free time I study algorithms and climb rocks."
social_username: csaroff

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
